 Network macgarcia_minha-rede-de-ponte  Creating
 Network macgarcia_minha-rede-de-ponte  Created
 Container banco_rinha  Creating
 Container banco_rinha  Created
 Container api2  Creating
 Container api1  Creating
 Container api1  Created
 Container api2  Created
 Container macgarcia-nginx-1  Creating
 Container macgarcia-nginx-1  Created
Attaching to api1, api2, banco_rinha, nginx-1
banco_rinha  | The files belonging to this database system will be owned by user "postgres".
banco_rinha  | This user must also own the server process.
banco_rinha  | 
banco_rinha  | The database cluster will be initialized with locale "en_US.utf8".
banco_rinha  | The default database encoding has accordingly been set to "UTF8".
banco_rinha  | The default text search configuration will be set to "english".
banco_rinha  | 
banco_rinha  | Data page checksums are disabled.
banco_rinha  | 
banco_rinha  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
banco_rinha  | creating subdirectories ... ok
banco_rinha  | selecting dynamic shared memory implementation ... posix
banco_rinha  | selecting default max_connections ... 100
banco_rinha  | selecting default shared_buffers ... 128MB
banco_rinha  | selecting default time zone ... Etc/UTC
banco_rinha  | creating configuration files ... ok
banco_rinha  | running bootstrap script ... ok
nginx-1      | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1      | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1      | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1      | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1      | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1      | /docker-entrypoint.sh: Configuration complete; ready for start up
banco_rinha  | performing post-bootstrap initialization ... ok
banco_rinha  | initdb: warning: enabling "trust" authentication for local connections
banco_rinha  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
banco_rinha  | syncing data to disk ... ok
banco_rinha  | 
banco_rinha  | 
banco_rinha  | Success. You can now start the database server using:
banco_rinha  | 
banco_rinha  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
banco_rinha  | 
banco_rinha  | waiting for server to start....2024-02-16 12:03:45.000 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
banco_rinha  | 2024-02-16 12:03:45.004 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
banco_rinha  | 2024-02-16 12:03:45.017 UTC [51] LOG:  database system was shut down at 2024-02-16 12:03:44 UTC
api2         |  __  __ _                                  _   
api2         | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api2         | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api2         | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api2         | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
banco_rinha  | 2024-02-16 12:03:45.025 UTC [48] LOG:  database system is ready to accept connections
banco_rinha  |  done
banco_rinha  | server started
banco_rinha  | CREATE DATABASE
banco_rinha  | 
banco_rinha  | 
banco_rinha  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
banco_rinha  | 
banco_rinha  | waiting for server to shut down...2024-02-16 12:03:45.194 UTC [48] LOG:  received fast shutdown request
banco_rinha  | .2024-02-16 12:03:45.214 UTC [48] LOG:  aborting any active transactions
banco_rinha  | 2024-02-16 12:03:45.218 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
banco_rinha  | 2024-02-16 12:03:45.219 UTC [49] LOG:  shutting down
banco_rinha  | 2024-02-16 12:03:45.223 UTC [49] LOG:  checkpoint starting: shutdown immediate
api1         |  __  __ _                                  _   
api1         | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api1         | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api1         | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api1         | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
banco_rinha  | 2024-02-16 12:03:45.718 UTC [49] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.388 s, sync=0.090 s, total=0.499 s; sync files=301, longest=0.061 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913078, redo lsn=0/1913078
banco_rinha  | 2024-02-16 12:03:45.726 UTC [48] LOG:  database system is shut down
banco_rinha  |  done
banco_rinha  | server stopped
banco_rinha  | 
banco_rinha  | PostgreSQL init process complete; ready for start up.
banco_rinha  | 
banco_rinha  | 2024-02-16 12:03:45.824 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
banco_rinha  | 2024-02-16 12:03:45.824 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
banco_rinha  | 2024-02-16 12:03:45.824 UTC [1] LOG:  listening on IPv6 address "::", port 5432
banco_rinha  | 2024-02-16 12:03:45.836 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
banco_rinha  | 2024-02-16 12:03:45.847 UTC [64] LOG:  database system was shut down at 2024-02-16 12:03:45 UTC
banco_rinha  | 2024-02-16 12:03:45.865 UTC [1] LOG:  database system is ready to accept connections
nginx-1      | 2024/02/16 12:03:47 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:03:47 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.3:8080/clientes/1/extrato", host: "localhost:9999"
api2         | [36m12:03:48.541[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api1         | [36m12:03:48.815[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
nginx-1      | 2024/02/16 12:03:49 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api2         | [36m12:03:50.023[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.pool.HikariPool[0;39m - HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@2228db21
api2         | [36m12:03:50.025[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Start completed.
api1         | [36m12:03:50.029[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.pool.HikariPool[0;39m - HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@2228db21
api1         | [36m12:03:50.031[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Start completed.
nginx-1      | 2024/02/16 12:03:51 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api1         | [36m12:03:51.928[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35morg.hibernate.Version[0;39m - HHH000412: Hibernate ORM core version [WORKING]
nginx-1      | 2024/02/16 12:03:53 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api2 exited with code 137
api1 exited with code 137
nginx-1      | 2024/02/16 12:03:55 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:03:57 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:04:59 [error] 29#29: *9 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:17 [error] 29#29: *9 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:22 [error] 29#29: *12 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:22 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:24 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:26 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:31 [error] 29#29: *16 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:31 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:36 [error] 29#29: *18 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:36 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:38 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:40 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:45 [error] 29#29: *22 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:45 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:50 [error] 29#29: *24 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:50 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:52 [error] 29#29: *26 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:05:54 [error] 29#29: *27 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:06:00 [error] 29#29: *28 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:06:00 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:06:05 [error] 29#29: *30 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.144.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1      | 2024/02/16 12:06:05 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
banco_rinha  | 2024-02-16 12:06:07.923 UTC [1] LOG:  received fast shutdown request
banco_rinha  | 2024-02-16 12:06:07.930 UTC [1] LOG:  aborting any active transactions
banco_rinha  | 2024-02-16 12:06:07.932 UTC [1] LOG:  background worker "logical replication launcher" (PID 67) exited with exit code 1
banco_rinha  | 2024-02-16 12:06:07.932 UTC [62] LOG:  shutting down
banco_rinha  | 2024-02-16 12:06:07.941 UTC [62] LOG:  checkpoint starting: shutdown immediate
banco_rinha  | 2024-02-16 12:06:08.001 UTC [62] LOG:  checkpoint complete: wrote 45 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.018 s, sync=0.020 s, total=0.070 s; sync files=12, longest=0.007 s, average=0.002 s; distance=261 kB, estimate=261 kB; lsn=0/19544B0, redo lsn=0/19544B0
banco_rinha  | 2024-02-16 12:06:08.005 UTC [1] LOG:  database system is shut down
banco_rinha exited with code 0
