 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container exemplo-db-1  Creating
 Container exemplo-db-1  Created
 Container exemplo-api02-1  Creating
 Container exemplo-api01-1  Creating
 Container exemplo-api01-1  Created
 Container exemplo-api02-1  Created
 Container exemplo-nginx-1  Creating
 Container exemplo-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | performing post-bootstrap initialization ... ok
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-02-07 22:15:28.725 UTC [48] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-07 22:15:28.730 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-07 22:15:28.738 UTC [51] LOG:  database system was shut down at 2024-02-07 22:15:28 UTC
db-1     | 2024-02-07 22:15:28.790 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | DO
db-1     | 
db-1     | 
db-1     | 2024-02-07 22:15:29.296 UTC [48] LOG:  received fast shutdown request
db-1     | waiting for server to shut down....2024-02-07 22:15:29.298 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-07 22:15:29.305 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-07 22:15:29.307 UTC [49] LOG:  shutting down
db-1     | 2024-02-07 22:15:29.310 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-07 22:15:29.498 UTC [49] LOG:  checkpoint complete: wrote 946 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.138 s, sync=0.040 s, total=0.191 s; sync files=319, longest=0.004 s, average=0.001 s; distance=4311 kB, estimate=4311 kB; lsn=0/19209A8, redo lsn=0/19209A8
db-1     | 2024-02-07 22:15:29.510 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-07 22:15:29.634 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-07 22:15:29.635 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-07 22:15:29.635 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-07 22:15:29.640 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-07 22:15:29.649 UTC [66] LOG:  database system was shut down at 2024-02-07 22:15:29 UTC
db-1     | 2024-02-07 22:15:29.656 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/07 22:15:30 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.19.0.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:30 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.19.0.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:32 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:34 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1  | 2024-02-07 22:15:35.031:INFO::main: Logging initialized @7980ms
api01-1  | 2024-02-07 22:15:35.032:INFO::main: Logging initialized @7981ms
nginx-1  | 2024/02/07 22:15:36 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:38 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:40 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:42 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.19.0.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:42 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.19.0.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:44 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:46 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:48 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/07 22:15:50 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1  | Feb 07, 2024 10:15:51 PM com.mchange.v2.log.MLog 
api02-1  | INFO: MLog clients using java 1.4+ standard logging.
api01-1  | Feb 07, 2024 10:15:51 PM com.mchange.v2.log.MLog 
api01-1  | INFO: MLog clients using java 1.4+ standard logging.
api02-1  | Feb 07, 2024 10:15:52 PM com.mchange.v2.c3p0.C3P0Registry 
api02-1  | INFO: Initializing c3p0-0.9.5.4 [built 23-March-2019 23:00:48 -0700; debug? true; trace: 10]
api01-1  | Feb 07, 2024 10:15:52 PM com.mchange.v2.c3p0.C3P0Registry 
api01-1  | INFO: Initializing c3p0-0.9.5.4 [built 23-March-2019 23:00:48 -0700; debug? true; trace: 10]
nginx-1  | 2024/02/07 22:15:52 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 172.19.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api01-1  | 2024-02-07 22:15:53.091:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
api02-1  | 2024-02-07 22:15:53.092:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
api02-1  | 2024-02-07 22:15:53.300:INFO:oejs.ServerConnector:main: Started ServerConnector@5c812e45{HTTP/1.1}{0.0.0.0:3000}
api02-1  | 2024-02-07 22:15:53.300:INFO:oejs.Server:main: Started @26250ms
api01-1  | 2024-02-07 22:15:53.302:INFO:oejs.ServerConnector:main: Started ServerConnector@6b0dcac6{HTTP/1.1}{0.0.0.0:3000}
api01-1  | 2024-02-07 22:15:53.302:INFO:oejs.Server:main: Started @26251ms
api01-1  | Started server on port 3000
api02-1  | Started server on port 3000
api02-1  | Feb 07, 2024 10:15:55 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource 
api02-1  | INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1bqsumbb1112wqffxsgiev|7fb46c10, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1bqsumbb1112wqffxsgiev|7fb46c10, idleConnectionTestPeriod -> 800, initialPoolSize -> 12, jdbcUrl -> jdbc:postgresql://db:5432/rinha?ApplicationName=rinha-web-server, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 3600, maxIdleTime -> 1800, maxIdleTimeExcessConnections -> 120, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {password=******, user=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
api01-1  | Feb 07, 2024 10:16:09 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource 
api01-1  | INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1bqsumcb1112wqfe1biblj6|7fb46c10, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1bqsumcb1112wqfe1biblj6|7fb46c10, idleConnectionTestPeriod -> 800, initialPoolSize -> 12, jdbcUrl -> jdbc:postgresql://db:5432/rinha?ApplicationName=rinha-web-server, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 3600, maxIdleTime -> 1800, maxIdleTimeExcessConnections -> 120, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {password=******, user=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1 exited with code 0
api02-1 exited with code 143
api01-1 exited with code 0
api01-1 exited with code 143
db-1     | 2024-02-07 22:20:18.281 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-07 22:20:18.283 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-07 22:20:18.286 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-07 22:20:18.286 UTC [64] LOG:  shutting down
db-1     | 2024-02-07 22:20:18.289 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-07 22:20:18.339 UTC [64] LOG:  checkpoint complete: wrote 605 buffers (3.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.035 s, sync=0.008 s, total=0.053 s; sync files=31, longest=0.003 s, average=0.001 s; distance=2084 kB, estimate=2084 kB; lsn=0/1B29C70, redo lsn=0/1B29C70
db-1     | 2024-02-07 22:20:18.347 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
