 Network brunolipe-a_default  Creating
 Network brunolipe-a_default  Created
 Container brunolipe-a-db-1  Creating
 Container brunolipe-a-db-1  Created
 Container brunolipe-a-api02-1  Creating
 Container brunolipe-a-api01-1  Creating
 Container brunolipe-a-api01-1  Created
 Container brunolipe-a-api02-1  Created
 Container brunolipe-a-nginx-1  Creating
 Container brunolipe-a-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | performing post-bootstrap initialization ... ok
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-02-17 23:19:43.509 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-17 23:19:43.512 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-17 23:19:43.523 UTC [52] LOG:  database system was shut down at 2024-02-17 23:19:42 UTC
db-1     | 2024-02-17 23:19:43.532 UTC [49] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1     | 
db-1     | waiting for server to shut down...2024-02-17 23:19:43.749 UTC [49] LOG:  received fast shutdown request
db-1     | .2024-02-17 23:19:43.753 UTC [49] LOG:  aborting any active transactions
db-1     | 2024-02-17 23:19:43.760 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
db-1     | 2024-02-17 23:19:43.760 UTC [50] LOG:  shutting down
db-1     | 2024-02-17 23:19:43.763 UTC [50] LOG:  checkpoint starting: shutdown immediate
api02-1  | {"level":30,"time":1708211983622,"pid":1,"hostname":"api02","msg":"started HTTP server on 0.0.0.0:3333"}
api01-1  | [ error ] connect ECONNREFUSED 192.168.0.2:5432
api01-1  |           at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
db-1     | 2024-02-17 23:19:44.273 UTC [50] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.396 s, sync=0.100 s, total=0.513 s; sync files=301, longest=0.064 s, average=0.001 s; distance=4256 kB, estimate=4256 kB; lsn=0/1912CE8, redo lsn=0/1912CE8
db-1     | 2024-02-17 23:19:44.277 UTC [49] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-17 23:19:44.877 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-17 23:19:44.877 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-17 23:19:44.877 UTC [1] LOG:  listening on IPv6 address "::", port 5432
api01-1 exited with code 1
db-1     | 2024-02-17 23:19:44.925 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-17 23:19:44.933 UTC [65] LOG:  database system was shut down at 2024-02-17 23:19:44 UTC
db-1     | 2024-02-17 23:19:44.940 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/17 23:19:48 [error] 30#30: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.0.3:3333/clientes/1/extrato", host: "localhost:9999"
db-1     | 2024-02-17 23:19:48.552 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:19:48.552 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708211988554,"pid":1,"hostname":"api02","request_id":"dki7weoi45an7ditiqs0n41d","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"dki7weoi45an7ditiqs0n41d","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:19:50.566 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:19:50.566 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708211990566,"pid":1,"hostname":"api02","request_id":"fu1oi4zza3xruqr722fuj4k8","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"fu1oi4zza3xruqr722fuj4k8","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:19:52.575 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:19:52.575 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708211992576,"pid":1,"hostname":"api02","request_id":"n5ovostcx2c49ucs8d5dy2nk","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"n5ovostcx2c49ucs8d5dy2nk","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:19:54.585 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:19:54.585 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708211994585,"pid":1,"hostname":"api02","request_id":"ujri03ui2h98u516cv9jvjfv","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"ujri03ui2h98u516cv9jvjfv","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:19:56.594 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:19:56.594 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708211996594,"pid":1,"hostname":"api02","request_id":"ietq56rf7guocd5fh96htfpn","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"ietq56rf7guocd5fh96htfpn","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:19:58.603 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:19:58.603 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708211998603,"pid":1,"hostname":"api02","request_id":"ai1iwp9ev7fefazz1pe68z17","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"ai1iwp9ev7fefazz1pe68z17","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:00.612 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:00.612 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212000612,"pid":1,"hostname":"api02","request_id":"bo5506t6hw401y5lz3ri9wmm","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"bo5506t6hw401y5lz3ri9wmm","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:02.621 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:02.621 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212002621,"pid":1,"hostname":"api02","request_id":"ivdhrlsr8239o462p17hj4zh","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"ivdhrlsr8239o462p17hj4zh","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
nginx-1  | 2024/02/17 23:20:07 [error] 30#30: *18 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.0.3:3333/clientes/1/extrato", host: "localhost:9999"
db-1     | 2024-02-17 23:20:07.693 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:07.693 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212007694,"pid":1,"hostname":"api02","request_id":"t2akncqac4n8dauag2lbrggw","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"t2akncqac4n8dauag2lbrggw","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:09.703 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:09.703 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212009704,"pid":1,"hostname":"api02","request_id":"e8c73qqxgbbwuggv04cv0nht","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"e8c73qqxgbbwuggv04cv0nht","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:11.712 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:11.712 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212011712,"pid":1,"hostname":"api02","request_id":"apqots6ltce2hghrfkwp96g0","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"apqots6ltce2hghrfkwp96g0","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:13.721 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:13.721 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212013722,"pid":1,"hostname":"api02","request_id":"t8myu9cgp2qltxmc367b5sug","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"t8myu9cgp2qltxmc367b5sug","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:15.731 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:15.731 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212015732,"pid":1,"hostname":"api02","request_id":"vj50t657g0cdiyehtvsajhjr","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"vj50t657g0cdiyehtvsajhjr","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:17.740 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:17.740 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212017741,"pid":1,"hostname":"api02","request_id":"kgbm58hv2l5ohhqpg4wwx1g2","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"kgbm58hv2l5ohhqpg4wwx1g2","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:19.750 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:19.750 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212019750,"pid":1,"hostname":"api02","request_id":"mn6udi18ljmj9r7hokuyju4k","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"mn6udi18ljmj9r7hokuyju4k","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:21.758 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:21.758 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212021759,"pid":1,"hostname":"api02","request_id":"jcxswpyqfoh7cm6hmxgsi105","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"jcxswpyqfoh7cm6hmxgsi105","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
nginx-1  | 2024/02/17 23:20:26 [error] 30#30: *35 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.0.3:3333/clientes/1/extrato", host: "localhost:9999"
db-1     | 2024-02-17 23:20:26.828 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:26.828 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212026828,"pid":1,"hostname":"api02","request_id":"g3ofr26xqohyxiv0clonxnpp","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"g3ofr26xqohyxiv0clonxnpp","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:28.837 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:28.837 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212028837,"pid":1,"hostname":"api02","request_id":"o3vxpcvqhfmgspbosd3yrmd5","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"o3vxpcvqhfmgspbosd3yrmd5","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:30.846 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:30.846 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212030846,"pid":1,"hostname":"api02","request_id":"j2pu30qzlz9b3xcals5lt13p","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"j2pu30qzlz9b3xcals5lt13p","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
db-1     | 2024-02-17 23:20:32.855 UTC [69] ERROR:  relation "clients" does not exist at character 15
db-1     | 2024-02-17 23:20:32.855 UTC [69] STATEMENT:  select * from "clients" where "id" = $1 limit $2
api02-1  | {"level":50,"time":1708212032855,"pid":1,"hostname":"api02","request_id":"bas8xzj35f2wbb7wm02rg2qj","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"bas8xzj35f2wbb7wm02rg2qj","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1 exited with code 0
api02-1 exited with code 0
db-1     | 2024-02-17 23:20:36.331 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-17 23:20:36.334 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-17 23:20:36.336 UTC [1] LOG:  background worker "logical replication launcher" (PID 68) exited with exit code 1
db-1     | 2024-02-17 23:20:36.337 UTC [63] LOG:  shutting down
db-1     | 2024-02-17 23:20:36.340 UTC [63] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-17 23:20:36.391 UTC [63] LOG:  checkpoint complete: wrote 43 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.029 s, total=0.055 s; sync files=12, longest=0.009 s, average=0.003 s; distance=94 kB, estimate=94 kB; lsn=0/192A500, redo lsn=0/192A500
db-1     | 2024-02-17 23:20:36.395 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
