 Container deno-cassiogangrel-postgres-1  Creating
 Container deno-cassiogangrel-postgres-1  Created
 Container deno-cassiogangrel-api01-1  Creating
 Container deno-cassiogangrel-api01-1  Created
 Container deno-cassiogangrel-api02-1  Creating
 Container deno-cassiogangrel-api02-1  Created
 Container deno-cassiogangrel-nginx-1  Creating
 nginx Published ports are discarded when using host network mode 
 Container deno-cassiogangrel-nginx-1  Created
Attaching to api01-1, api02-1, nginx-1, postgres-1
postgres-1  | The files belonging to this database system will be owned by user "postgres".
postgres-1  | This user must also own the server process.
postgres-1  | 
postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
postgres-1  | The default database encoding has accordingly been set to "UTF8".
postgres-1  | The default text search configuration will be set to "english".
postgres-1  | 
postgres-1  | Data page checksums are disabled.
postgres-1  | 
postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres-1  | creating subdirectories ... ok
postgres-1  | selecting dynamic shared memory implementation ... posix
postgres-1  | selecting default max_connections ... 100
postgres-1  | selecting default shared_buffers ... 128MB
postgres-1  | selecting default time zone ... Etc/UTC
postgres-1  | creating configuration files ... ok
postgres-1  | running bootstrap script ... ok
api01-1     | Listening on http://localhost:8080/
api01-1     | Server ouvindo na porta: 8080
api01-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api01-1     |     this.#conn = await Deno.connect(options);
api01-1     | [0m[31m                 ^[0m
api01-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api01-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api01-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api01-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api01-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api01-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api01-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api01-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
nginx-1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
api02-1     | Listening on http://localhost:8081/
api02-1     | Server ouvindo na porta: 8081
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1     | /docker-entrypoint.sh: Configuration complete; ready for start up
postgres-1  | performing post-bootstrap initialization ... ok
api02-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api02-1     |     this.#conn = await Deno.connect(options);
api02-1     | [0m[31m                 ^[0m
api02-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api02-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api02-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api02-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api02-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api02-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api02-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api02-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api01-1 exited with code 0
api01-1     | Listening on http://localhost:8080/
api01-1     | Server ouvindo na porta: 8080
api01-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api01-1     |     this.#conn = await Deno.connect(options);
api01-1     | [0m[31m                 ^[0m
api01-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api01-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api01-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api01-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api01-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api01-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api01-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api01-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api02-1 exited with code 0
postgres-1  | initdb: warning: enabling "trust" authentication for local connections
postgres-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres-1  | syncing data to disk ... ok
postgres-1  | 
postgres-1  | 
postgres-1  | Success. You can now start the database server using:
postgres-1  | 
postgres-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres-1  | 
api01-1 exited with code 0
api02-1 exited with code 0
postgres-1  | waiting for server to start....2024-02-16 06:05:22.990 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1  | 2024-02-16 06:05:22.993 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-02-16 06:05:23.003 UTC [51] LOG:  database system was shut down at 2024-02-16 06:05:21 UTC
postgres-1  | 2024-02-16 06:05:23.010 UTC [48] LOG:  database system is ready to accept connections
postgres-1  |  done
postgres-1  | server started
api01-1     | Listening on http://localhost:8080/
api01-1     | Server ouvindo na porta: 8080
api01-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api01-1     |     this.#conn = await Deno.connect(options);
api01-1     | [0m[31m                 ^[0m
api01-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api01-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api01-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api01-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api01-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api01-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api01-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api01-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api02-1     | Listening on http://localhost:8081/
api02-1     | Listening on http://localhost:8081/
api02-1     | Server ouvindo na porta: 8081
api02-1     | Server ouvindo na porta: 8081
api02-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api02-1     |     this.#conn = await Deno.connect(options);
api02-1     | [0m[31m                 ^[0m
api02-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api02-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api02-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api02-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api02-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api02-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api02-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api02-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api02-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api02-1     |     this.#conn = await Deno.connect(options);
api02-1     | [0m[31m                 ^[0m
api02-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api02-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api02-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api02-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api02-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api02-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api02-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api02-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
postgres-1  | CREATE DATABASE
postgres-1  | 
postgres-1  | 
postgres-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
postgres-1  | CREATE EXTENSION
postgres-1  | CREATE TABLE
postgres-1  | CREATE TABLE
postgres-1  | CREATE FUNCTION
postgres-1  | CREATE TRIGGER
postgres-1  | DO
postgres-1  | 
postgres-1  | 
postgres-1  | waiting for server to shut down....2024-02-16 06:05:23.911 UTC [48] LOG:  received fast shutdown request
postgres-1  | 2024-02-16 06:05:23.915 UTC [48] LOG:  aborting any active transactions
postgres-1  | 2024-02-16 06:05:23.917 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
postgres-1  | 2024-02-16 06:05:23.917 UTC [49] LOG:  shutting down
postgres-1  | 2024-02-16 06:05:23.922 UTC [49] LOG:  checkpoint starting: shutdown immediate
nginx-1     | 2024/02/16 06:05:23 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/16 06:05:23 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8081/clientes/1/extrato", host: "localhost:9999"
api01-1 exited with code 0
api02-1 exited with code 0
api01-1     | Listening on http://localhost:8080/
api01-1     | Server ouvindo na porta: 8080
api01-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api01-1     |     this.#conn = await Deno.connect(options);
api01-1     | [0m[31m                 ^[0m
api01-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api01-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api01-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api01-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api01-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api01-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api01-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api01-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api01-1     | Listening on http://localhost:8080/
api01-1     | Server ouvindo na porta: 8080
api01-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api01-1     |     this.#conn = await Deno.connect(options);
api01-1     | [0m[31m                 ^[0m
api01-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api01-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api01-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api01-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api01-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api01-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api01-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api01-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api01-1     | Listening on http://localhost:8080/
api01-1     | Server ouvindo na porta: 8080
api01-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api01-1     |     this.#conn = await Deno.connect(options);
api01-1     | [0m[31m                 ^[0m
api01-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api01-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api01-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api01-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api01-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api01-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api01-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api01-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api01-1     | Listening on http://localhost:8080/
api01-1     | Server ouvindo na porta: 8080
api01-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api01-1     |     this.#conn = await Deno.connect(options);
api01-1     | [0m[31m                 ^[0m
api01-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api01-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api01-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api01-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api01-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api01-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api01-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api01-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api02-1     | Listening on http://localhost:8081/
api02-1     | Server ouvindo na porta: 8081
api02-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api02-1     |     this.#conn = await Deno.connect(options);
api02-1     | [0m[31m                 ^[0m
api02-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api02-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api02-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api02-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api02-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api02-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api02-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api02-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api02-1     | Listening on http://localhost:8081/
api02-1     | Server ouvindo na porta: 8081
api02-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api02-1     |     this.#conn = await Deno.connect(options);
api02-1     | [0m[31m                 ^[0m
api02-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api02-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api02-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api02-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api02-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api02-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api02-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api02-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api02-1     | Listening on http://localhost:8081/
api02-1     | Server ouvindo na porta: 8081
api02-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api02-1     |     this.#conn = await Deno.connect(options);
api02-1     | [0m[31m                 ^[0m
api02-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api02-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api01-1 exited with code 1
api02-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api02-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api02-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api02-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api02-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api02-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api02-1     | Listening on http://localhost:8081/
api02-1     | Server ouvindo na porta: 8081
api02-1     | [0m[1m[31merror[0m: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
api02-1     |     this.#conn = await Deno.connect(options);
api02-1     | [0m[31m                 ^[0m
api02-1     |     at async [0m[1m[3mObject.connect[0m ([0m[36mext:deno_net/01_net.js[0m:[0m[33m579[0m:[0m[33m55[0m)
api02-1     |     at async [0m[1m[3mConnection.#openConnection[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m246[0m:[0m[33m18[0m)
api02-1     |     at async [0m[1m[3mConnection.#startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m322[0m:[0m[33m7[0m)
api02-1     |     at async [0m[1m[3mConnection.startup[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/connection/connection.ts[0m:[0m[33m474[0m:[0m[33m11[0m)
api02-1     |     at async [0m[1m[3mPoolClient.connect[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/client.ts[0m:[0m[33m233[0m:[0m[33m7[0m)
api02-1     |     at async [0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m191[0m:[0m[33m9[0m
api02-1     |     at async [0m[1m[3mPromise.all (index 0)[0m
api02-1     |     at async [0m[1m[3mPool.#initialize[0m ([0m[36mhttps://deno.land/x/postgres@v.0.18.1/pool.ts[0m:[0m[33m198[0m:[0m[33m7[0m)
api02-1 exited with code 1
postgres-1  | .2024-02-16 06:05:25.277 UTC [49] LOG:  checkpoint complete: wrote 937 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.699 s, sync=0.596 s, total=1.360 s; sync files=306, longest=0.149 s, average=0.002 s; distance=4295 kB, estimate=4295 kB; lsn=0/191C790, redo lsn=0/191C790
postgres-1  | 2024-02-16 06:05:25.281 UTC [48] LOG:  database system is shut down
postgres-1  |  done
postgres-1  | server stopped
postgres-1  | 
postgres-1  | PostgreSQL init process complete; ready for start up.
postgres-1  | 
postgres-1  | 2024-02-16 06:05:25.337 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1  | 2024-02-16 06:05:25.337 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1  | 2024-02-16 06:05:25.337 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1  | 2024-02-16 06:05:25.343 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-02-16 06:05:25.350 UTC [66] LOG:  database system was shut down at 2024-02-16 06:05:25 UTC
postgres-1  | 2024-02-16 06:05:25.356 UTC [1] LOG:  database system is ready to accept connections
api01-1     | Listening on http://localhost:8080/
api01-1     | Server ouvindo na porta: 8080
nginx-1     | 2024/02/16 06:05:25 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1     | Listening on http://localhost:8081/
api02-1     | Server ouvindo na porta: 8081
nginx-1     | 2024/02/16 06:05:28 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/16 06:05:30 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/16 06:05:32 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
postgres-1  | 2024-02-16 06:05:59.328 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:05:59.328 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:05:59.328 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:05:59.605 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:05:59.605 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:05:59.605 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:05:59.779 UTC [109] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:05:59.779 UTC [109] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:05:59.779 UTC [109] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:00.227 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:00.227 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:00.227 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:00.261 UTC [109] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:00.261 UTC [109] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:00.261 UTC [109] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:00.296 UTC [109] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:00.296 UTC [109] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:00.296 UTC [109] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:00.331 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:00.331 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:00.331 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:00.850 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:00.850 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:00.850 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:01.012 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:01.012 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:01.012 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:01.077 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:01.077 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:01.077 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:01.823 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:01.823 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:01.823 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:01.883 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:01.883 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:01.883 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:02.066 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:02.066 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:02.066 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:02.427 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:02.427 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:02.427 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:02.856 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:02.856 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:02.856 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:02.970 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:02.970 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:02.970 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:03.056 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:03.056 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:03.056 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:03.084 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:03.084 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:03.084 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:03.113 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:03.113 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:03.113 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:03.170 UTC [89] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:03.170 UTC [89] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:03.170 UTC [89] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:03.534 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:03.534 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:03.534 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:03.831 UTC [90] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:03.831 UTC [90] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:03.831 UTC [90] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:04.317 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:04.317 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:04.317 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:04.504 UTC [90] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:04.504 UTC [90] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:04.504 UTC [90] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:04.556 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:04.556 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:04.556 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:04.610 UTC [90] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:04.610 UTC [90] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:04.610 UTC [90] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:04.768 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:04.768 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
postgres-1  | 2024-02-16 06:06:04.768 UTC [110] STATEMENT:  
postgres-1  | 	        INSERT INTO transactions 
postgres-1  | 	        (transaction_id, customer_id, value, type, description, created_at)
postgres-1  | 	        VALUES
postgres-1  | 	        ($1, $2, $3, $4, $5, $6)
postgres-1  | 	        
postgres-1  | 2024-02-16 06:06:04.951 UTC [110] ERROR:  Saldo insuficiente para esta transação!
postgres-1  | 2024-02-16 06:06:04.951 UTC [110] CONTEXT:  PL/pgSQL function update_balance() line 7 at RAISE
