 Container kiro-tagama-db-1  Creating
 Container kiro-tagama-db-1  Created
 Container kiro-tagama-api02-3  Creating
 Container kiro-tagama-api02-1  Creating
 Container kiro-tagama-api02-2  Creating
 Container kiro-tagama-api01-2  Creating
 Container kiro-tagama-api01-1  Creating
 Container kiro-tagama-api01-3  Creating
 Container kiro-tagama-api01-2  Created
 Container kiro-tagama-api02-3  Created
 Container kiro-tagama-api02-1  Created
 Container kiro-tagama-api02-2  Created
 Container kiro-tagama-api01-1  Created
 Container kiro-tagama-api01-3  Created
 Container kiro-tagama-nginx-1  Creating
 Container kiro-tagama-nginx-1  Created
Attaching to api01-1, api01-2, api01-3, api02-1, api02-2, api02-3, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
api02-1  | node:net:1893
api02-1  |     const ex = new UVExceptionWithHostPort(err, 'listen', address, port);
api02-1  |                ^
api02-1  | 
api02-1  | Error: listen EADDRINUSE: address already in use 127.0.0.1:9999
api02-1  |     at Server.setupListenHandle [as _listen2] (node:net:1893:16)
api02-1  |     at listenInCluster (node:net:1941:12)
api02-1  |     at GetAddrInfoReqWrap.doListen [as callback] (node:net:2096:7)
api02-1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
api02-1  |   code: 'EADDRINUSE',
api02-1  |   errno: -98,
api02-1  |   syscall: 'listen',
api02-1  |   address: '127.0.0.1',
api02-1  |   port: 9999
api02-1  | }
api02-1  | 
api02-1  | Node.js v21.6.1
api02-2  | node:net:1893
api02-2  |     const ex = new UVExceptionWithHostPort(err, 'listen', address, port);
api02-2  |                ^
api02-2  | 
api02-2  | Error: listen EADDRINUSE: address already in use 127.0.0.1:9999
api02-2  |     at Server.setupListenHandle [as _listen2] (node:net:1893:16)
api02-2  |     at listenInCluster (node:net:1941:12)
api02-2  |     at GetAddrInfoReqWrap.doListen [as callback] (node:net:2096:7)
api02-2  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
api02-2  |   code: 'EADDRINUSE',
api02-2  |   errno: -98,
api02-2  |   syscall: 'listen',
api02-2  |   address: '127.0.0.1',
api02-2  |   port: 9999
api02-2  | }
api02-2  | 
api02-2  | Node.js v21.6.1
api01-1  | node:net:1893
api01-1  |     const ex = new UVExceptionWithHostPort(err, 'listen', address, port);
api01-1  |                ^
api01-1  | 
api01-1  | Error: listen EADDRINUSE: address already in use 127.0.0.1:9999
api01-1  |     at Server.setupListenHandle [as _listen2] (node:net:1893:16)
api01-1  |     at listenInCluster (node:net:1941:12)
api01-1  |     at GetAddrInfoReqWrap.doListen [as callback] (node:net:2096:7)
api01-1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
api01-1  |   code: 'EADDRINUSE',
api01-1  |   errno: -98,
api01-1  |   syscall: 'listen',
api01-1  |   address: '127.0.0.1',
api01-1  |   port: 9999
api01-1  | }
api01-1  | 
api01-1  | Node.js v21.6.1
db-1     | performing post-bootstrap initialization ... ok
api02-3  | node:net:1893
api02-3  |     const ex = new UVExceptionWithHostPort(err, 'listen', address, port);
api02-3  |                ^
api02-3  | 
api02-3  | Error: listen EADDRINUSE: address already in use 127.0.0.1:9999
api02-3  |     at Server.setupListenHandle [as _listen2] (node:net:1893:16)
api02-3  |     at listenInCluster (node:net:1941:12)
api02-3  |     at GetAddrInfoReqWrap.doListen [as callback] (node:net:2096:7)
api02-3  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
api02-3  |   code: 'EADDRINUSE',
api02-3  |   errno: -98,
api02-3  |   syscall: 'listen',
api02-3  |   address: '127.0.0.1',
api02-3  |   port: 9999
api02-3  | }
api02-3  | 
api02-3  | Node.js v21.6.1
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
api01-2  | node:net:1893
api01-2  |     const ex = new UVExceptionWithHostPort(err, 'listen', address, port);
api01-2  |                ^
api01-2  | 
api01-2  | Error: listen EADDRINUSE: address already in use 127.0.0.1:9999
api01-2  |     at Server.setupListenHandle [as _listen2] (node:net:1893:16)
api01-2  |     at listenInCluster (node:net:1941:12)
api01-2  |     at GetAddrInfoReqWrap.doListen [as callback] (node:net:2096:7)
api01-2  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
api01-2  |   code: 'EADDRINUSE',
api01-2  |   errno: -98,
api01-2  |   syscall: 'listen',
api01-2  |   address: '127.0.0.1',
api01-2  |   port: 9999
api01-2  | }
api01-2  | 
api01-2  | Node.js v21.6.1
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1  | 2024/02/16 10:49:49 [emerg] 1#1: host not found in upstream "api01:3000" in /etc/nginx/nginx.conf:10
nginx-1  | nginx: [emerg] host not found in upstream "api01:3000" in /etc/nginx/nginx.conf:10
api02-1 exited with code 1
api02-3 exited with code 1
api01-2 exited with code 1
api02-2 exited with code 1
nginx-1 exited with code 1
api01-1 exited with code 1
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-16 10:49:51.058 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-16 10:49:51.063 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-16 10:49:51.071 UTC [51] LOG:  database system was shut down at 2024-02-16 10:49:49 UTC
db-1     | 2024-02-16 10:49:51.083 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | DO
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-02-16 10:49:51.294 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-16 10:49:51.297 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-16 10:49:51.298 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-16 10:49:51.299 UTC [49] LOG:  shutting down
db-1     | 2024-02-16 10:49:51.301 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-16 10:49:51.799 UTC [49] LOG:  checkpoint complete: wrote 944 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.270 s, sync=0.218 s, total=0.501 s; sync files=310, longest=0.153 s, average=0.001 s; distance=4314 kB, estimate=4314 kB; lsn=0/1921210, redo lsn=0/1921210
db-1     | 2024-02-16 10:49:51.804 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-16 10:49:51.922 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-16 10:49:51.922 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-16 10:49:51.922 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-16 10:49:51.928 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-16 10:49:51.935 UTC [66] LOG:  database system was shut down at 2024-02-16 10:49:51 UTC
db-1     | 2024-02-16 10:49:51.941 UTC [1] LOG:  database system is ready to accept connections
db-1     | 2024-02-16 10:52:52.620 UTC [78] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.623 UTC [98] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.623 UTC [96] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.623 UTC [95] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.623 UTC [93] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.623 UTC [83] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.625 UTC [86] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.625 UTC [82] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.627 UTC [87] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2024-02-16 10:52:52.627 UTC [97] LOG:  could not receive data from client: Connection reset by peer
api01-3 exited with code 137
db-1     | 2024-02-16 10:54:04.138 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-16 10:54:04.144 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-16 10:54:04.146 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-16 10:54:04.146 UTC [64] LOG:  shutting down
db-1     | 2024-02-16 10:54:04.150 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-16 10:54:04.313 UTC [64] LOG:  checkpoint complete: wrote 379 buffers (2.3%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.065 s, sync=0.076 s, total=0.167 s; sync files=33, longest=0.062 s, average=0.003 s; distance=9634 kB, estimate=9634 kB; lsn=0/2289DB0, redo lsn=0/2289DB0
db-1     | 2024-02-16 10:54:04.316 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
